//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YurdumNet_MasterPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Degerlendirmeler
    {
        public int DegerlendirmeID { get; set; }
        public string Yorum { get; set; }
        public int Rating { get; set; }
        public int YurtID { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public string Mail { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    
        public virtual Yurtlar Yurtlar { get; set; }
    }
}
