//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YurdumNet_MasterPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Universiteler
    {
        public int UniversiteID { get; set; }
        public string UniversiteAdi { get; set; }
        public int SehirID { get; set; }
        public string Konum { get; set; }
    
        public virtual Sehirler Sehirler { get; set; }
    }
}
