//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YurdumNet_MasterPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YurtFotograflari
    {
        public int FotoID { get; set; }
        public int YurtID { get; set; }
        public string FotoYolu { get; set; }
    
        public virtual Yurtlar Yurtlar { get; set; }
    }
}
