//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YurdumNet_MasterPage.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class YurtEkle
    {
        public int Id { get; set; }
        public string Adı { get; set; }
        public string Soyadi { get; set; }
        public string Telefon { get; set; }
        public string YurtAdi { get; set; }
        public string Adres { get; set; }
        public string FotoYolu { get; set; }
       public HttpPostedFileBase FotoDosyasi { get; set; }
    }
}
