//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YurdumNet_MasterPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YurtOzellikleri
    {
        public int YurtID { get; set; }
        public string wi_fi { get; set; }
        public string Kahvalti { get; set; }
        public string Aksam_Yemegi { get; set; }
        public string Kantin { get; set; }
        public string Tv_Odasi { get; set; }
        public string Bir_Kisilik { get; set; }
        public string Iki_Kisilik { get; set; }
        public string Uc_Kisilik { get; set; }
        public string Dort_Kisilik { get; set; }
        public string Merkezi_Isitma { get; set; }
        public string Revir { get; set; }
        public string Mini_Buzdolabi { get; set; }
        public string Yangin_Merdiveni { get; set; }
        public string Utu_Odasi { get; set; }
        public string Camasir_Odasi { get; set; }
        public string Bilgisayar_Odasi { get; set; }
        public string Bahce { get; set; }
        public string Kitaplik { get; set; }
        public string Klima { get; set; }
        public string Asansor { get; set; }
        public string Jenerator { get; set; }
        public string Siginak { get; set; }
        public string Kamera_Kayit { get; set; }
        public string Kartli_Giris { get; set; }
        public string Fitness_Salonu { get; set; }
        public string Masa_Tenisi { get; set; }
        public string Bilardo { get; set; }
        public string Havuz { get; set; }
        public string Satranc { get; set; }
        public string OzellikAdi { get; set; }
    
        public virtual Yurtlar Yurtlar { get; set; }
    }
}
