//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YurdumNet_MasterPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yurtlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Yurtlar()
        {
            this.Degerlendirmeler = new HashSet<Degerlendirmeler>();
            this.YurtFotograflari = new HashSet<YurtFotograflari>();
        }
    
        public int YurtID { get; set; }
        public string YurtAdi { get; set; }
        public int SehirID { get; set; }
        public string Adres { get; set; }
        public string Konum { get; set; }
        public int YurtSahibiID { get; set; }
        public string Telefon { get; set; }
        public string FotografYolu { get; set; }
        public decimal AylikFiyat { get; set; }
        public string YurtTipi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Degerlendirmeler> Degerlendirmeler { get; set; }
        public virtual Sehirler Sehirler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YurtFotograflari> YurtFotograflari { get; set; }
        public virtual YurtSahipleri YurtSahipleri { get; set; }
        public virtual YurtOzellikleri YurtOzellikleri { get; set; }
    }
}
